version: '3.9'

services:
  postgres:
    image: postgres
    container_name: crawl
    ports:
      - '5435:5432'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crawl
    volumes:
      - crawl:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  crawl:
